series: Basic OpenGL with GLFW
title: Spot Lighting
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use spot lights to light objects within a cone.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Point Lighting